[phases.setup]
nixPkgs = ["python38", "postgresql", "pipenv"]

[phases.install]
cmd = "nix-shell -p python -m venv --copies /opt/venv && ./otp/venv/bin/activate && pip install -r requirements.txt"

[phases.start]
cmd = "gunicorn run:app"